Repository linkfrg/ignis, pull requests merged in 2024-12, with the labels that each got.

#43 feat(nix): remove submodules for nix build
  docs/user/installation.rst
  nix/ignis.nix
Labels: nix

#44 fix(nix): add GStreamer & PipeWire to build inputs
  nix/ignis.nix
Labels: nix

#53 feat: IgnisApp.add_icons()
  docs/user/faq.rst
  ignis/app.py
Labels: enhancement

#59 fix: UPower Device State always return false
  ignis/services/upower/constants.py
  ignis/services/upower/device.py
Labels: bug

#28 feat: Bluetooth Service
  docs/api/services/bluetooth.rst
  ignis/exceptions.py
  ignis/services/bluetooth/__init__.py
  ignis/services/bluetooth/_imports.py
  ignis/services/bluetooth/constants.py
  ignis/services/bluetooth/device.py
  ignis/services/bluetooth/service.py
  stubs/gi/repository/GnomeBluetooth.pyi
Labels: enhancement
